---
-
  name: Create env file
  template: src=env.j2
            dest={{ www_root }}/{{ item.site_name }}/web/.env
  with_items: sites
-
  name: Clone repo
  git: repo={{ item.repo.url }}
       dest=/tmp/sites/{{ item.site_name }}
       version={{ item.repo.branch }}
       force=yes
       depth=1
  with_items: sites
-
  name: Copy repo
  command: "cp -r /tmp/sites/{{ item.site_name }}/. {{ www_root }}/{{ item.site_name }}/web"
  with_items: sites
