---
-
  file: "path=\"{{ www_root }}/{{ item.site_name }}/web\" owner=\"{{ item.user | default(user) }}\" group=www-data mode=0755 state=directory"
  name: "Create web root of sites"
  with_items: sites
-
  file: "path=\"{{ www_root }}/{{ item.site_name }}/logs\" owner=\"{{ item.user | default(user) }}\" group=www-data mode=0755 state=directory"
  name: "Create logs folder of sites"
  with_items: sites
