---
-
  group: "name=sudo state=present"
  name: "Ensure sudo group is present"
-
  lineinfile: "dest=/etc/sudoers state=present regexp=\"^%sudo\" line=\"%sudo ALL=(ALL:ALL) ALL\" validate=\"/usr/sbin/visudo -cf %s\""
  name: "Ensure sudo group has sudo privileges"
-
  name: "Setup sudo users"
  user: "name=\"{{ item.user }}\" group=\"{{ item.groups[0] }}\" groups=\"{{ item.groups | join(',') }}\" password=\"{{ sudoer_passwords[ item.user ] }}\" shell=/bin/bash update_password=always state=present"
  with_items: sudoers
-
  authorized_key: "user=\"{{ item.user }}\" key=\"{{ lookup('file', item.public_key | default(ssh_public_key)) }}\""
  name: "Adding public key to server"
  with_items: sudoers
