---
-
  connection: local
  hosts: localhost
  name: "Launch staging server"
  tasks:
    -
      ec2:
        assign_public_ip: true
        count_tag:
          Name: staging.dev
        exact_count: 1
        group: "All Traffic"
        image: ami-9a562df2
        instance_tags:
          Name: staging.dev
        instance_type: t2.micro
        key_name: j2-staging
        region: us-east-1
        vpc_subnet_id: subnet-5138dd08
        wait: true
      name: "Launch instances"
      register: ec2
    -
      local_action: "add_host hostname={{ item.public_ip }} groupname=staging"
      name: "Add instances to host group"
      with_items: ec2.instances
