---
-
  apt_repository: "repo=\"ppa:duggan/composer\" update_cache=yes"
  name: "Add Composer PPA"
-
  apt: "name=php5-composer state=present force=yes"
  name: "Install Composer"
-
  name: "Composer self update"
  shell: "composer self-update"
