---
-
  group: "name=\"{{ deploy_group }}\" state=present"
  name: "Setup deploy group"
-
  name: "Setup deploy user"
  user: "name=\"{{ deploy_user }}\" group=\"{{ deploy_group }}\" groups=\"{{ deploy_groups }}\" state=present shell=/bin/bash"
-
  authorized_key: "user=\"{{ deploy_user }}\" key=\"{{ item }}\""
  name: "Adding public key to server"
  with_file: deploy_keys
