---
-
  apt_repository: "repo=\"ppa:ondrej/php5-5.6\" update_cache=yes"
  name: "Add PHP 5.6 PPA"
-
  apt: "name=\"{{ item }}\" state=present force=yes"
  name: "Install PHP 5.6"
  with_items:
    - php5-common
    - php5-fpm
    - php5-mysqlnd
    - php5-xmlrpc
    - php5-mcrypt
    - php5-curl
    - php5-gd
    - php5-cli
    - php-pear
    - php5-dev
    - php5-imap
-
  name: "Start php5-fpm service"
  service: "name=php5-fpm state=started enabled=true"
-
  file: "path=/var/run/php5-fpm/ state=directory"
  name: "Create socket directory"
-
  command: "mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.disabled creates=/etc/php5/fpm/pool.d/www.disabled"
  name: "Disable default pool"
  notify: "restart php-fpm"
  when: disable_default_pool
-
  name: "Add php.ini template"
  notify: "restart php-fpm"
  template: "src=\"php.ini.j2\" dest=\"/etc/php5/fpm/php.ini\""
