---
-
  apt: "name=\"{{ item }}\" state=present update_cache=yes"
  name: "Install memcached"
  with_items:
    - python-selinux
    - memcached
    - php5-memcached
-
  name: "Copy the client configuration file"
  notify: "restart memcached"
  template: "src=memcached.j2 dest=/etc/memcached.conf"
-
  name: "Set the max open file descriptors"
  sysctl: "name=fs.file-max value=\"{{ memcached_fs_file_max }}\" state=present"
-
  name: "Start the memcached service"
  service: "name=memcached state=started enabled=yes"
